### ISSUE TITLE
DAO Core enchancement

### ISSUE THREAD

**Issue by EvgenRad81** [airalab/learning-center#11]
Предлагаю добавить в ядро счетчик кол-ва модулей и события по добавлению\удалению модулей.

**Comment by akru** [comment]
А почему здесь обсуждение, а не в https://github.com/airalab/core/issues?

Насчет эвентов согласен, а зачем счетчик?

**Comment by EvgenRad81** [comment]
Обсуждение тут, потому что я протупил))
Счетчик, просто для инфы, особой функции у него не предусматривается

**Comment by akru** [comment]
Создал эквивалент в соответсвующем репозитории(`Core`), тут закрываю.
