### ISSUE TITLE
From Morden to Ropsten

### ISSUE THREAD

**Issue by ensrationis** [airalab/learning-center#17]
@EvgenRad81 Жень, с тебя тестовые эфира для Саши.
@vol4tim Саш, с тебя создание контрактов учебного центра в новой тестовой сети и замена их адресов в уроках. Prt sc менять не будем пока что, чтобы не тратить время.

**Comment by EvgenRad81** [comment]
Я могу после переноса обновить скрины.

**Comment by EvgenRad81** [comment]
Обновлены все уроки. 
Найдены ошибки:
1) Не понятно как работает проверка 7-го урока. Не получилось завершить.
2) 0-й урок не отправляет эзеры по ping.

**Comment by EvgenRad81** [comment]
0-й урок поправили. Отправил туда 50 Eth.
